- README.md
- requirements.txt
This makes the README instructions simpler.
> Centralize dependency installation to requirements.txt

- README.md
- python/iree_torch/__init__.py
- tools/torchscript_e2e_main.py
- tools/torchscript_e2e_test.sh
This is the minimum skeleton to make things reusable between the e2e
testing and examples. There is still API design work to be done here to
better serve use cases and to provide a more comprehensive experience
(rather than somewhat low-level tools).
> Start factoring some code into a `python/` directory.

- torchdynamo_poc/resnet18.py
This commit adds an example script showing how to run resnet18 using
torchdynamo and IREE as the backend.
> Add resnet18 with torchdynamo example

- python/iree_torch/__init__.py
We don't have a way to deal with the ABI mismatch caused by changing the
types.
> Remove --iree-flow-demote-i64-to-i32 -- it broke a bunch of tests.

- torchdynamo_poc/torchbench.py
- torchdynamo_poc/torchdynamo_test.py
This commit adds some unit tests for the torch-MLIR compiler used by
torchdynamo, and fixes a few errors in the way that tuple returns were
being handled.
> Add unit tests to torchdynamo torch-mlir compiler

- python/iree_torch/__init__.py
The interface for `VmModule.from_flatbuffer` in iree-runtime was
[recently changed](https://github.com/iree-org/iree/commit/9aa83eda3bd531ef74174cb7e7e7e9a1f4450336)
to take an instance argument in addition to the flatbuffer. This
commit updates `load_vmfb` to use this new interface.
> Update `load_vmfb` to use new `from_flatbuffer` interface

- torchdynamo_poc/bert.py
- torchdynamo_poc/torchbench.py
- torchdynamo_poc/utils.py
This commit adds the file `utils.py` to share the logic used by
`torchbench.py` to compile, time, and check the torchbench models with
other models not in torchbench. This commit also adds an script that runs
`Bert` on IREE and PyTorch eager.
> Move most of torchbench.py code to new utils.py + bert.py example

- torchdynamo_poc/README.md
- torchdynamo_poc/requirements.txt
This commit adds a file with the `pip` requirements needed to run
torchbench.py, as well as a `README.md` file with instructions on
everything else that needs to be installed to run the script.
> Add requirements.txt and README.md to torchdynamo_POC

- torchdynamo_poc/torchbench.py
TorchDynamo now requires that `torchdynamo.reset()` be called when the
compiler passed to `torchdynamo.optimize` is changed.
> Add torchdynamo.reset() when changing compilers

- torchdynamo_poc/requirements.txt
If `-f` is used in `pip` rather than `--extra-index-url`, the right
`pillow` dependency is not installed.
> Pass pytorch nightly url using --extra-index-url

- torchdynamo_poc/README.md
- torchdynamo_poc/requirements.txt
- Use `python -m pip` consistently.
- Add `torchbenchmark` to PYTHONPATH
- Install iree-torch itself in the venv
Also, constrain the `pillow` version. This is the same workaround as we
have in the main iree-torch/requirements.txt
> [torchdynamo_poc] Improve README

- python/iree_torch/__init__.py
- torchdynamo_poc/utils.py
Mean/standard deviation aren't great for performance tracking, since
they don't really have a very useful meaning in this context. Using
quantiles is more precise and interpretable.
Also, update to `llvm-cpu` backend name.
> [torchdynamo_poc] Print somewhat nicer timings

- torchdynamo_poc/bert.py
- torchdynamo_poc/torchbench.py
- torchdynamo_poc/utils.py
It does not make much sense to have `print_time_stats` be responsible of removing warmup iteration times from the iteration times list. This commit removes the `warmup_iters` argument from the function.
> Remove warmup_iters arg from print_time_stats

- python/iree_torch/__init__.py
- torchdynamo_poc/utils.py
In order to get the best performance on CUDA, the CUDA LLVM target
architecture must be specified in the IREE compiler. This commit adds
support for specifying such a flag. In addition, it sets the flag to
`sm_80` in the TorchDynamo `utils.py`, since that target architecture
is needed to use NVIDIA's tensorcore.
> Add CUDA LLVM target arch flag to `compile_to_vmfb`

- torchdynamo_poc/torchbench.py
- torchdynamo_poc/utils.py
A previous commit introduced a bug in `print_time_stats` by removing the line that turns the input list into a torch tensor. This commit adds that back in.
> Make COMPILED/EAGER_ITERATION_TIMES local + bugfix print_time_stats

- torchdynamo_poc/utils.py
This commit updates the `check_results` function to use `torch.allclose` to compare tensors.
> Use `torch.allclose` to check results

- torchdynamo_poc/README.md
This commit adds some instructions for running the `bert.py` script. It also does some formatting of the README and adds a description of what the `torchbench.py` file does.
> Add README instructions for bert.py

- torchdynamo_poc/bert.py
- torchdynamo_poc/torchbench.py
Using the context manager with TorchDynamo will soon be deprecated (https://github.com/pytorch/torchdynamo/commit/a2665c5fe11b91bb8d811303df52acd47bce5af2). The preferred method is to use the `torchdynamo.optimize` decorator. This commit updates the scripts to use the decorator.
> Use torchdynamo decorator instead of context manager

- README.md
- examples/bert.py
- tools/e2e_main.py
This was breaking tests and the bert example.
> Fix obsolete dylib backend, replacing with llvm-cpu.

- torchdynamo_poc/README.md
Functorch is in the process of getting moved into the PyTorch repository. This commit updates the installation instructions to install the `functorch` in the PyTorch directory rather than the `functorch` in the `functorch` repository, which can often fail to
install. See: https://github.com/pytorch/pytorch/issues/84882
> Update functorch installation instructions

- torchdynamo_poc/utils.py
Commit 47e390a036da1fe288272073446c37cd3c01b9b7 discarded some changes that had been added by commit
87e043d31c3d5248d70ebe79ce407bbe6ed3c270. This commit adds the changes back.
> Add back lost changes to `_unwrap_single_tuple_return`

- torchdynamo_poc/utils.py
The op `torch.allclose` results in a runtime error if the two input tensors are not on the same device. This commit moves the input tensors of `torch.allclose` to the CPU device.
> Move input tensors to CPU device in `check_results`

- torchdynamo_poc/bert.py
- torchdynamo_poc/torchbench.py
- torchdynamo_poc/utils.py
This commit updates `torch_mlir_compiler` to return a compiler rather than the compiled graph. This makes it easier to specify the compiler to torchdynamo. For example:
```python
@torchdynamo.optimize(torch_mlir_compiler(use_tracing=False))
def some_func():
pass
```
> Make torch_mlir_compiler return a torchdynamo compatible compiler

- torchdynamo_poc/bert.py
- torchdynamo_poc/utils.py
This commit adds support for running `bert.py` without needing to use tracing.
> Add scripting support to `bert.py`

- torchdynamo_poc/TorchDynamo Demo.ipynb
- torchdynamo_poc/utils.py
This commit adds a Jupyter notebook with some example of how to use TorchDynamo with Torch-MLIR + IREE, as well as how the process compares with the current Torch-MLIR Python API. This commit also adds some verbose support to the `make_torch_mlir_compiler` function to have a better idea of what is going on behind the scenes when running the Jupyter notebook.
> Add jupyter notebook with TorchDynamo demo

- .github/workflows/test_nightly_packages.yml
- requirements.txt
- tools/e2e_main.py
Aten_EmbeddingBagExample_basic is failing for mysterious reasons that don't reproduce with a local build. Unclear why.
> Attempt to bring back the failing CI.

- examples/bert.ipynb
This is working now.  See https://github.com/llvm/torch-mlir/issues/1493
Also, fix a small typo.
> Remove py3.9 or py3.10 requirement from bert notebook.

- .github/workflows/test_nightly_packages.yml
This fixes the syntax -- it was being interpreted as 3.1
> Use Python 3.10

- examples/regression.py
No longer needed after https://github.com/llvm/torch-mlir/commit/e2de20575f92264f1131039a4d1393833a893f4c
Also, remove unnecessary use_tracing argument.
> Remove unncessary strip_overloads.
